In [152]:
A = np.array([
    [63, 134, 79, 35, 152, 31, 146, 72, 9, 81, 105, 26, 79, 35, 152, 31, 146, 72, 8, 81], 
    [99, 95, 61, 92, 131, 163, 177, 76, 10, 1, 9, 173, 61, 92, 131, 163, 177, 76, 10, 1], 
    [111, 198, 90, 96, 26, 88, 77, 138, 5, 136, 185, 92, 90, 96, 26, 88, 77, 138, 5, 136], 
    [40, 8, 104, 175, 132, 36, 169, 66, 191, 64, 7, 121, 104, 175, 132, 36, 169, 66, 191, 64], 
    [58, 12, 43, 198, 190, 77, 171, 61, 130, 67, 52, 165, 43, 198, 190, 77, 171, 61, 130, 67], 
    [89, 80, 82, 159, 126, 101, 58, 136, 97, 7, 106, 47, 82, 159, 126, 101, 58, 136, 97, 7], 
    [160, 81, 151, 158, 106, 28, 196, 100, 38, 34, 174, 160, 151, 158, 106, 28, 196, 100, 38, 34], 
    [145, 85, 146, 146, 106, 74, 27, 162, 41, 42, 53, 45, 146, 146, 106, 74, 27, 162, 41, 42], 
    [149, 167, 50, 93, 162, 169, 121, 75, 66, 136, 117, 28, 50, 93, 162, 169, 121, 75, 66, 136], 
    [164, 197, 154, 16, 134, 175, 148, 124, 157, 191, 5, 151, 154, 16, 134, 175, 148, 124, 157, 191], 
    [192, 31, 74, 132, 141, 65, 138, 20, 167, 30, 90, 160, 74, 132, 141, 65, 138, 20, 167, 30], 
    [174, 140, 157, 127, 176, 9, 91, 20, 83, 103, 179, 104, 157, 127, 176, 9, 91, 20, 83, 103], 
    [147, 53, 99, 20, 87, 8, 113, 136, 65, 40, 196, 29, 99, 20, 87, 8, 113, 136, 65, 40], 
    [107, 41, 8, 86, 195, 43, 155, 20, 160, 112, 144, 97, 8, 86, 195, 43, 155, 20, 160, 112], 
    [18, 107, 184, 139, 107, 173, 110, 45, 60, 89, 183, 8, 184, 139, 107, 173, 110, 45, 60, 89], 
    [52, 115, 124, 78, 2, 112, 69, 76, 53, 74, 190, 142, 124, 78, 2, 112, 69, 76, 53, 74], 
    [161, 54, 136, 100, 193, 126, 13, 120, 99, 33, 13, 134, 136, 100, 193, 126, 13, 120, 99, 33], 
    [179, 145, 140, 25, 82, 173, 78, 122, 151, 187, 183, 150, 140, 25, 82, 173, 78, 122, 151, 187], 
    [118, 130, 175, 171, 52, 144, 3, 64, 172, 132, 153, 189, 175, 171, 52, 144, 3, 64, 172, 132], 
    [91, 82, 58, 133, 16, 59, 53, 122, 60, 174, 193, 64, 58, 133, 16, 59, 53, 122, 60, 174]
])

In [153]:
print(A)

[[ 63 134  79  35 152  31 146  72   9  81 105  26  79  35 152  31 146  72
    8  81]
 [ 99  95  61  92 131 163 177  76  10   1   9 173  61  92 131 163 177  76
   10   1]
 [111 198  90  96  26  88  77 138   5 136 185  92  90  96  26  88  77 138
    5 136]
 [ 40   8 104 175 132  36 169  66 191  64   7 121 104 175 132  36 169  66
  191  64]
 [ 58  12  43 198 190  77 171  61 130  67  52 165  43 198 190  77 171  61
  130  67]
 [ 89  80  82 159 126 101  58 136  97   7 106  47  82 159 126 101  58 136
   97   7]
 [160  81 151 158 106  28 196 100  38  34 174 160 151 158 106  28 196 100
   38  34]
 [145  85 146 146 106  74  27 162  41  42  53  45 146 146 106  74  27 162
   41  42]
 [149 167  50  93 162 169 121  75  66 136 117  28  50  93 162 169 121  75
   66 136]
 [164 197 154  16 134 175 148 124 157 191   5 151 154  16 134 175 148 124
  157 191]
 [192  31  74 132 141  65 138  20 167  30  90 160  74 132 141  65 138  20
  167  30]
 [174 140 157 127 176   9  91  20  83 103 179 104 157 127 176   9

In [154]:
B = np.array([
     [84, 62, 175, 38, 159, 123, 90, 115, 142, 163, 80, 82, 62, 175, 38, 159, 123, 90, 115, 142], 
     [58, 70, 156, 44, 80, 180, 53, 43, 122, 4, 21, 23, 70, 156, 44, 80, 180, 53, 43, 122], 
     [173, 0, 64, 47, 155, 194, 8, 32, 196, 196, 96, 71, 0, 64, 47, 155, 194, 8, 32, 196], 
     [147, 167, 49, 152, 129, 167, 25, 7, 110, 106, 123, 79, 167, 49, 152, 129, 167, 25, 7, 110],
     [142, 125, 80, 168, 152, 2, 194, 100, 6, 56, 50, 127, 125, 80, 168, 152, 2, 194, 100, 6], 
     [193, 129, 53, 72, 103, 92, 142, 23, 102, 70, 104, 23, 129, 53, 72, 103, 92, 142, 23, 102], 
     [80, 67, 77, 198, 140, 60, 161, 33, 150, 15, 166, 192, 67, 77, 198, 140, 60, 161, 33, 150], 
     [25, 6, 118, 132, 84, 25, 187, 24, 189, 161, 167, 100, 6, 118, 132, 84, 25, 187, 24, 189], 
     [177, 5, 31, 133, 3, 163, 143, 128, 184, 133, 167, 94, 5, 31, 133, 3, 163, 143, 128, 184], 
     [75, 130, 67, 152, 162, 74, 108, 42, 97, 124, 165, 102, 130, 67, 152, 162, 74, 108, 42, 97], 
     [182, 144, 54, 145, 3, 62, 51, 83, 16, 79, 82, 104, 144, 54, 145, 3, 62, 51, 83, 16], 
     [3, 97, 19, 17, 127, 36, 128, 32, 1, 96, 199, 189, 97, 19, 17, 127, 36, 128, 32, 1], 
     [40, 154, 186, 41, 79, 151, 13, 196, 75, 166, 160, 104, 154, 186, 41, 79, 151, 13, 196, 75], 
     [91, 130, 110, 164, 141, 181, 193, 58, 56, 98, 145, 196, 130, 110, 164, 141, 181, 193, 58, 56], 
     [34, 55, 180, 103, 118, 16, 27, 95, 169, 70, 198, 8, 55, 180, 103, 118, 16, 27, 95, 169], 
     [164, 70, 164, 147, 95, 195, 9, 107, 155, 55, 14, 159, 70, 164, 147, 95, 195, 9, 107, 155], 
     [52, 27, 98, 180, 93, 32, 146, 32, 132, 123, 60, 166, 27, 98, 180, 93, 32, 146, 32, 132], 
     [189, 134, 69, 187, 42, 199, 60, 26, 70, 95, 186, 132, 134, 69, 187, 42, 199, 60, 26, 70],
     [135, 93, 94, 182, 139, 46, 122, 52, 74, 112, 9, 188, 93, 94, 182, 139, 46, 122, 52, 74], 
     [62, 8, 13, 146, 115, 135, 29, 138, 85, 133, 104, 118, 8, 13, 146, 115, 135, 29, 138, 85]
])

In [155]:
print(B)

[[ 84  62 175  38 159 123  90 115 142 163  80  82  62 175  38 159 123  90
  115 142]
 [ 58  70 156  44  80 180  53  43 122   4  21  23  70 156  44  80 180  53
   43 122]
 [173   0  64  47 155 194   8  32 196 196  96  71   0  64  47 155 194   8
   32 196]
 [147 167  49 152 129 167  25   7 110 106 123  79 167  49 152 129 167  25
    7 110]
 [142 125  80 168 152   2 194 100   6  56  50 127 125  80 168 152   2 194
  100   6]
 [193 129  53  72 103  92 142  23 102  70 104  23 129  53  72 103  92 142
   23 102]
 [ 80  67  77 198 140  60 161  33 150  15 166 192  67  77 198 140  60 161
   33 150]
 [ 25   6 118 132  84  25 187  24 189 161 167 100   6 118 132  84  25 187
   24 189]
 [177   5  31 133   3 163 143 128 184 133 167  94   5  31 133   3 163 143
  128 184]
 [ 75 130  67 152 162  74 108  42  97 124 165 102 130  67 152 162  74 108
   42  97]
 [182 144  54 145   3  62  51  83  16  79  82 104 144  54 145   3  62  51
   83  16]
 [  3  97  19  17 127  36 128  32   1  96 199 189  97  19  17 127

In [82]:
import numpy as np
import cv2

In [83]:
# Question 2a
A_trans = np.transpose(A)
B_trans = np.transpose(B)

In [84]:
print("Transpose of A: " ,A_trans,'\n')
print("Transpose of B: " ,B_trans)

Transpose of A:  [[ 63  99 111  40  58  89 160 145 149 164 192 174 147 107  18  52 161 179
  118  91]
 [134  95 198   8  12  80  81  85 167 197  31 140  53  41 107 115  54 145
  130  82]
 [ 79  61  90 104  43  82 151 146  50 154  74 157  99   8 184 124 136 140
  175  58]
 [ 35  92  96 175 198 159 158 146  93  16 132 127  20  86 139  78 100  25
  171 133]
 [152 131  26 132 190 126 106 106 162 134 141 176  87 195 107   2 193  82
   52  16]
 [ 31 163  88  36  77 101  28  74 169 175  65   9   8  43 173 112 126 173
  144  59]
 [146 177  77 169 171  58 196  27 121 148 138  91 113 155 110  69  13  78
    3  53]
 [ 72  76 138  66  61 136 100 162  75 124  20  20 136  20  45  76 120 122
   64 122]
 [  9  10   5 191 130  97  38  41  66 157 167  83  65 160  60  53  99 151
  172  60]
 [ 81   1 136  64  67   7  34  42 136 191  30 103  40 112  89  74  33 187
  132 174]
 [105   9 185   7  52 106 174  53 117   5  90 179 196 144 183 190  13 183
  153 193]
 [ 26 173  92 121 165  47 160  45  28 151 160 10

In [89]:
print(A.shape)
print(B.shape)

(20, 20)
(20, 20)


In [90]:
# Question 2b
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B) 

In [91]:
print("Inverse of A: " ,A_inv,'\n')
print("Inverse of B: " ,B_inv)

Inverse of A:  [[-8.43223619e-17 -1.07793294e-03 -1.38935116e-02 -1.01739453e-02
   2.24401776e-03 -4.17321945e-03 -5.37644613e-03  6.59605477e-03
   5.97517851e-04 -2.62557619e-03  8.95466151e-03  1.52055653e-03
   2.82831706e-03 -2.96682936e-03 -1.02592586e-02 -3.61284346e-03
   2.49209147e-03  7.75394862e-03 -6.51041667e-03  5.38966468e-03]
 [-3.94574708e-16 -1.38828633e-03  1.14533623e-02  5.55314534e-03
  -3.81778742e-03  9.71800434e-03  1.04121475e-03 -1.66594360e-02
   1.04121475e-02  4.16485900e-03 -1.11062907e-02  2.08242950e-02
  -1.38828633e-03 -1.38828633e-02  1.04121475e-03  6.24728850e-03
   6.94143167e-04 -9.71800434e-03  0.00000000e+00  6.94143167e-03]
 [ 1.91499164e+00 -1.25299748e+13  7.10984006e+12  3.67248362e+12
  -2.48312622e+12  1.79503201e+13  4.91610858e+12 -2.57408166e+13
  -5.30288575e+12  4.21832958e+12  1.42485448e+13  6.73288094e+12
  -1.65835034e+13 -1.68089265e+13  4.68546201e+12  3.83680946e+12
   1.73379014e+13  6.61666883e+12 -2.65684624e+13  1.208255

In [103]:
# Question 2c
add_AB = np.array(A + B)
add_BA = np.array(B + A)

In [104]:
print("A+B : " ,add_AB,'\n')
print("B+A: " ,add_BA,'\n')
if np.array_equal(add_AB,add_BA):
    print("Both addition are same")
else:
    print("Both addition are different")

A+B :  [[147 196 254  73 311 154 236 187 151 244 185 108 141 210 190 190 269 162
  123 223]
 [157 165 217 136 211 343 230 119 132   5  30 196 131 248 175 243 357 129
   53 123]
 [284 198 154 143 181 282  85 170 201 332 281 163  90 160  73 243 271 146
   37 332]
 [187 175 153 327 261 203 194  73 301 170 130 200 271 224 284 165 336  91
  198 174]
 [200 137 123 366 342  79 365 161 136 123 102 292 168 278 358 229 173 255
  230  73]
 [282 209 135 231 229 193 200 159 199  77 210  70 211 212 198 204 150 278
  120 109]
 [240 148 228 356 246  88 357 133 188  49 340 352 218 235 304 168 256 261
   71 184]
 [170  91 264 278 190  99 214 186 230 203 220 145 152 264 238 158  52 349
   65 231]
 [326 172  81 226 165 332 264 203 250 269 284 122  55 124 295 172 284 218
  194 320]
 [239 327 221 168 296 249 256 166 254 315 170 253 284  83 286 337 222 232
  199 288]
 [374 175 128 277 144 127 189 103 183 109 172 264 218 186 286  68 200  71
  250  46]
 [177 237 176 144 303  45 219  52  84 199 378 293 254 146 

In [105]:
# Question 2d
sub_AB = np.array(A - B)
sub_BA = np.array(B - A)

In [164]:
print("A-B : " ,sub_AB,'\n')
print("B-A: " ,sub_BA,'\n')
if np.array_equal(sub_AB,sub_BA):
    print("Both Subtraction are same")
else:
    print("Both Subtraction are different")

A-B :  [[ -21   72  -96   -3   -7  -92   56  -43 -133  -82   25  -56   17 -140
   114 -128   23  -18 -107  -61]
 [  41   25  -95   48   51  -17  124   33 -112   -3  -12  150   -9  -64
    87   83   -3   23  -33 -121]
 [ -62  198   26   49 -129 -106   69  106 -191  -60   89   21   90   32
   -21  -67 -117  130  -27  -60]
 [-107 -159   55   23    3 -131  144   59   81  -42 -116   42  -63  126
   -20  -93    2   41  184  -46]
 [ -84 -113  -37   30   38   75  -23  -39  124   11    2   38  -82  118
    22  -75  169 -133   30   61]
 [-104  -49   29   87   23    9  -84  113   -5  -63    2   24  -47  106
    54   -2  -34   -6   74  -95]
 [  80   14   74  -40  -34  -32   35   67 -112   19    8  -32   84   81
   -92 -112  136  -61    5 -116]
 [ 120   79   28   14   22   49 -160  138 -148 -119 -114  -55  140   28
   -26  -10    2  -25   17 -147]
 [ -28  162   19  -40  159    6  -22  -53 -118    3  -50  -66   45   62
    29  166  -42  -68  -62  -48]
 [  89   67   87 -136  -28  101   40   82   60  

In [108]:
# Question 2e
mul_AB = A.dot(B)
mul_BA = B.dot(A)

In [111]:
print("A*B : \n" , mul_AB,'\n')
print("B*A : \n" , mul_BA,'\n')
if np.array_equal(mul_AB,mul_BA):
    print("Both multiplication are equal")
else:
    print("Both multiplication are different")

A*B : 
 [[143678 122789 156180 194897 166134 138707 144983 105749 165596 141851
  174372 162836 122789 156180 194897 166134 138707 144983 105749 165596]
 [175004 151996 181744 212424 204611 173870 187347 105661 194944 158156
  205933 211300 151996 181744 212424 204611 173870 187347 105661 194944]
 [192652 166686 176457 221124 190863 221722 161229 120133 193960 190903
  215696 202872 166686 176457 221124 190863 221722 161229 120133 193960]
 [210139 167376 177794 277225 229285 204265 222379 135089 222153 216662
  250853 261514 167376 177794 277225 229285 204265 222379 135089 222153]
 [218104 189480 189248 292795 245909 198285 238505 136141 218012 207256
  263351 270034 189480 189248 292795 245909 198285 238505 136141 218012]
 [213073 168535 183397 234745 189337 206024 181215 119998 198644 186718
  213686 203722 168535 183397 234745 189337 206024 181215 119998 198644]
 [212491 191838 210050 263758 238002 223311 212916 141153 225605 229956
  266631 264164 191838 210050 263758 238002 223311

In [112]:
c1 = 2
c2 = 0.5

In [113]:
# Question 2f
c1_A = c1*A
c2_A = c2*A
c1_B = c1*B
c2_B = c2*B


In [114]:
print("c1*A with c1 = 2 : \n" , c1_A,'\n')
print("c2*A with c2 = 0.5 : \n" , c2_A,'\n')
print("c1*B with c1 = 2 : \n" , c1_B,'\n')
print("c2*B with c2 = 0.5 : \n" , c2_B,'\n')

c1*A with c1 = 2 : 
 [[126 268 158  70 304  62 292 144  18 162 210  52 158  70 304  62 292 144
   16 162]
 [198 190 122 184 262 326 354 152  20   2  18 346 122 184 262 326 354 152
   20   2]
 [222 396 180 192  52 176 154 276  10 272 370 184 180 192  52 176 154 276
   10 272]
 [ 80  16 208 350 264  72 338 132 382 128  14 242 208 350 264  72 338 132
  382 128]
 [116  24  86 396 380 154 342 122 260 134 104 330  86 396 380 154 342 122
  260 134]
 [178 160 164 318 252 202 116 272 194  14 212  94 164 318 252 202 116 272
  194  14]
 [320 162 302 316 212  56 392 200  76  68 348 320 302 316 212  56 392 200
   76  68]
 [290 170 292 292 212 148  54 324  82  84 106  90 292 292 212 148  54 324
   82  84]
 [298 334 100 186 324 338 242 150 132 272 234  56 100 186 324 338 242 150
  132 272]
 [328 394 308  32 268 350 296 248 314 382  10 302 308  32 268 350 296 248
  314 382]
 [384  62 148 264 282 130 276  40 334  60 180 320 148 264 282 130 276  40
  334  60]
 [348 280 314 254 352  18 182  40 166 206 35

In [115]:
# Question 2g
div_c1_A = A/c1
div_c2_A = A/c2
div_c1_B = B/c1
div_c2_B = B/c2

In [116]:
print("A/c1 with c1 = 2 : \n" , div_c1_A,'\n')
print("A/c2 with c2 = 0.5 : \n" , div_c2_A,'\n')
print("B/c1 with c1 = 2 : \n" , div_c1_B,'\n')
print("B/c2 with c2 = 0.5 : \n" , div_c2_B,'\n')

A/c1 with c1 = 2 : 
 [[31.5 67.  39.5 17.5 76.  15.5 73.  36.   4.5 40.5 52.5 13.  39.5 17.5
  76.  15.5 73.  36.   4.  40.5]
 [49.5 47.5 30.5 46.  65.5 81.5 88.5 38.   5.   0.5  4.5 86.5 30.5 46.
  65.5 81.5 88.5 38.   5.   0.5]
 [55.5 99.  45.  48.  13.  44.  38.5 69.   2.5 68.  92.5 46.  45.  48.
  13.  44.  38.5 69.   2.5 68. ]
 [20.   4.  52.  87.5 66.  18.  84.5 33.  95.5 32.   3.5 60.5 52.  87.5
  66.  18.  84.5 33.  95.5 32. ]
 [29.   6.  21.5 99.  95.  38.5 85.5 30.5 65.  33.5 26.  82.5 21.5 99.
  95.  38.5 85.5 30.5 65.  33.5]
 [44.5 40.  41.  79.5 63.  50.5 29.  68.  48.5  3.5 53.  23.5 41.  79.5
  63.  50.5 29.  68.  48.5  3.5]
 [80.  40.5 75.5 79.  53.  14.  98.  50.  19.  17.  87.  80.  75.5 79.
  53.  14.  98.  50.  19.  17. ]
 [72.5 42.5 73.  73.  53.  37.  13.5 81.  20.5 21.  26.5 22.5 73.  73.
  53.  37.  13.5 81.  20.5 21. ]
 [74.5 83.5 25.  46.5 81.  84.5 60.5 37.5 33.  68.  58.5 14.  25.  46.5
  81.  84.5 60.5 37.5 33.  68. ]
 [82.  98.5 77.   8.  67.  87.5 74.  62

In [118]:
# Question 2h
ele_AB = np.multiply(A,B)
ele_BA = np.multiply(B,A)

In [119]:
print("A.*B : " ,ele_AB,'\n')
print("B.*A: " ,ele_BA,'\n')
if np.array_equal(ele_AB,ele_BA):
    print("Both multiplication are same")
else:
    print("Both multiplication are different")

A.*B :  [[ 5292  8308 13825  1330 24168  3813 13140  8280  1278 13203  8400  2132
   4898  6125  5776  4929 17958  6480   920 11502]
 [ 5742  6650  9516  4048 10480 29340  9381  3268  1220     4   189  3979
   4270 14352  5764 13040 31860  4028   430   122]
 [19203     0  5760  4512  4030 17072   616  4416   980 26656 17760  6532
      0  6144  1222 13640 14938  1104   160 26656]
 [ 5880  1336  5096 26600 17028  6012  4225   462 21010  6784   861  9559
  17368  8575 20064  4644 28223  1650  1337  7040]
 [ 8236  1500  3440 33264 28880   154 33174  6100   780  3752  2600 20955
   5375 15840 31920 11704   342 11834 13000   402]
 [17177 10320  4346 11448 12978  9292  8236  3128  9894   490 11024  1081
  10578  8427  9072 10403  5336 19312  2231   714]
 [12800  5427 11627 31284 14840  1680 31556  3300  5700   510 28884 30720
  10117 12166 20988  3920 11760 16100  1254  5100]
 [ 3625   510 17228 19272  8904  1850  5049  3888  7749  6762  8851  4500
    876 17228 13992  6216   675 30294   984

In [125]:
# Question 2i
f_ele = 3
print("locations of 3 in A are: \n",np.argwhere(A==f_ele),'\n')
print("locations of 3 in B are: \n",np.argwhere(B==f_ele))

locations of 3 in A are: 
 [[18  6]
 [18 16]] 

locations of 3 in B are: 
 [[ 8  4]
 [ 8 15]
 [10  4]
 [10 15]
 [11  0]]


In [157]:
# Question 2j
f_ele = 3

print("locations of 3 in A are: \n",np.argwhere(A==f_ele),'\n')
print("locations of 3 in B are: \n",np.argwhere(B==f_ele))

loc_A = np.argwhere(A==f_ele)
loc_B = np.argwhere(B==f_ele)

first_loc_A = loc_A[0]
first_loc_B = loc_B[0]

print("First location of 3 in A is : ",first_loc_A, '\n')

print("First location of 3 in B is : ",first_loc_B,'\n')

x_A = first_loc_A[0];
y_A = first_loc_A[1];

x_B = first_loc_B[0];
y_B = first_loc_B[1];

new_A = np.copy(A)
new_B = np.copy(B)

new_A[x_A][y_A]*=2
new_B[x_B][y_B]*=2

print("Modified Matrix A is: \n" ,new_A,'\n')
print("Modified Matrix A is: \n" ,new_B,'\n')

locations of 3 in A are: 
 [[18  6]
 [18 16]] 

locations of 3 in B are: 
 [[ 8  4]
 [ 8 15]
 [10  4]
 [10 15]
 [11  0]]
First location of 3 in A is :  [18  6] 

First location of 3 in B is :  [8 4] 

Modified Matrix A is: 
 [[ 63 134  79  35 152  31 146  72   9  81 105  26  79  35 152  31 146  72
    8  81]
 [ 99  95  61  92 131 163 177  76  10   1   9 173  61  92 131 163 177  76
   10   1]
 [111 198  90  96  26  88  77 138   5 136 185  92  90  96  26  88  77 138
    5 136]
 [ 40   8 104 175 132  36 169  66 191  64   7 121 104 175 132  36 169  66
  191  64]
 [ 58  12  43 198 190  77 171  61 130  67  52 165  43 198 190  77 171  61
  130  67]
 [ 89  80  82 159 126 101  58 136  97   7 106  47  82 159 126 101  58 136
   97   7]
 [160  81 151 158 106  28 196 100  38  34 174 160 151 158 106  28 196 100
   38  34]
 [145  85 146 146 106  74  27 162  41  42  53  45 146 146 106  74  27 162
   41  42]
 [149 167  50  93 162 169 121  75  66 136 117  28  50  93 162 169 121  75
   66 136]
 [164 197 

In [163]:
# Question 2k

# MY BIRTHDAY
my_db = 20

f_ele = 13

loc_A = np.argwhere(A==f_ele)
loc_B = np.argwhere(B==f_ele)

print("Total locations of 13 in A are" , len(loc_A) , "\n which are as follow: \n",np.argwhere(A==f_ele),'\n')
print("Total locations of 13 in B are" , len(loc_B) , "\n which are as follow: \n",np.argwhere(B==f_ele))

new_A = np.copy(A)
new_B = np.copy(B)

new_A = np.where(new_A==f_ele, my_db, new_A) 
new_B = np.where(new_B==f_ele, my_db, new_B)

print("Modified Matrix A is: \n" ,new_A,'\n')
print("Modified Matrix A is: \n" ,new_B,'\n')

Total locations of 13 in A are 3 
 which are as follow: 
 [[16  6]
 [16 10]
 [16 16]] 

Total locations of 13 in B are 4 
 which are as follow: 
 [[12  6]
 [12 17]
 [19  2]
 [19 13]]
Modified Matrix A is: 
 [[ 63 134  79  35 152  31 146  72   9  81 105  26  79  35 152  31 146  72
    8  81]
 [ 99  95  61  92 131 163 177  76  10   1   9 173  61  92 131 163 177  76
   10   1]
 [111 198  90  96  26  88  77 138   5 136 185  92  90  96  26  88  77 138
    5 136]
 [ 40   8 104 175 132  36 169  66 191  64   7 121 104 175 132  36 169  66
  191  64]
 [ 58  12  43 198 190  77 171  61 130  67  52 165  43 198 190  77 171  61
  130  67]
 [ 89  80  82 159 126 101  58 136  97   7 106  47  82 159 126 101  58 136
   97   7]
 [160  81 151 158 106  28 196 100  38  34 174 160 151 158 106  28 196 100
   38  34]
 [145  85 146 146 106  74  27 162  41  42  53  45 146 146 106  74  27 162
   41  42]
 [149 167  50  93 162 169 121  75  66 136 117  28  50  93 162 169 121  75
   66 136]
 [164 197 154  16 134 175 14